using System.Text.RegularExpressions;
using Xunit;

namespace Prdb.Hashing.Tests;

/// <summary>
/// Pins the perceptual hash to the values Stash would produce. These are the level 1 and
/// level 2 test vectors published in <c>docs/video-hashing.md</c>.
/// <para>
/// The expectations below were generated by running the real dependency chain Stash uses
/// — <c>corona10/goimagehash</c> v1.1.0, <c>disintegration/imaging</c> v1.6.2 and
/// <c>nfnt/resize</c> at the revision Stash pins — over the images
/// <see cref="ProceduralImages"/> builds. Both sides generate their pixels from the same
/// documented formula, so no binary fixtures are needed and the comparison is exact
/// rather than approximate.
/// </para>
/// <para>
/// A failure here means these hashes stopped being comparable with Stash's and with
/// anything else in the ecosystem. It is not a test to adjust to a new value, and it is
/// not a test to change alongside the code it covers.
/// </para>
/// </summary>
public class PerceptualHashReferenceTests
{
    [Theory]
    [InlineData("noise", 160, 90, "c1f4572a54f72c98")]
    [InlineData("gradient", 160, 90, "d5808a2f7e2f7415")]
    [InlineData("noise", 160, 120, "c1fc562254f32e99")]
    [InlineData("gradient", 160, 67, "d5808a2f7e2f7c05")]
    [InlineData("noise", 200, 113, "c6c8573156f124be")]
    [InlineData("gradient", 320, 180, "d5808a2f5e2f7c15")]
    public void Montage_MatchesGoimagehash(string kind, int tileWidth, int tileHeight, string expected)
    {
        var frames = Enumerable
            .Range(0, FrameMontage.FrameCount)
            .Select(i => ProceduralImages.Create(kind, i, tileWidth, tileHeight))
            .ToList();

        Assert.Equal(expected, PerceptualHash.ComputeHex(FrameMontage.Combine(frames)));
    }

    [Theory]
    [InlineData("noise", 1, 800, 450, "9d0b303b629cf8d9")]
    [InlineData("gradient", 1, 800, 450, "85421fb227ae7ca9")]
    [InlineData("gradient", 3, 64, 64, "956d4a8d7ad12953")]
    [InlineData("gradient", 5, 33, 17, "95b368d3050bde5c")]
    [InlineData("noise", 9, 37, 23, "8dd8dc85c7d84791")]
    [InlineData("noise", 4, 65, 64, "9a6367da8e971541")]
    [InlineData("gradient", 11, 127, 71, "dbe9c01d5a918357")]
    [InlineData("gradient", 2, 1, 1, "8000000000000000")]
    public void SingleImage_MatchesGoimagehash(string kind, int seed, int width, int height, string expected)
        => Assert.Equal(expected, PerceptualHash.ComputeHex(ProceduralImages.Create(kind, seed, width, height)));

    /// <summary>
    /// A flat image has no AC energy, so every coefficient but the DC one is zero. That
    /// pins the bit order on its own: only the coefficient at index 0 exceeds the
    /// threshold, and it must land in the most significant bit. It also pins the DC
    /// coefficient being kept — a pipeline that discards it returns zero here.
    /// </summary>
    [Fact]
    public void FlatImage_SetsOnlyTheDcBit()
        => Assert.Equal("8000000000000000", PerceptualHash.ComputeHex(ProceduralImages.Flat(800, 450, 128)));

    [Fact]
    public void ComputeHex_IsAlways16LowercaseHexCharacters()
    {
        var hash = PerceptualHash.ComputeHex(ProceduralImages.Create("noise", 1, 800, 450));

        // The API validates pHash against ^[0-9A-Fa-f]{16}$.
        Assert.Matches(new Regex("^[0-9a-f]{16}$"), hash);
    }

    [Fact]
    public void Resize_ToTheSameSize_ReturnsTheInputUntouched()
    {
        var image = ProceduralImages.Noise(1, 64, 64);

        // nfnt short-circuits this case, and it is observable: filtering would re-quantise
        // the pixels even at scale 1.
        Assert.Same(image, BilinearResizer.Resize(image, 64, 64));
    }
}
