using System.Text.RegularExpressions;
using Xunit;

namespace Prdb.Hashing.Tests;

/// <summary>
/// Pins the perceptual hash to the published test vectors — the level 1 and level 2 rows
/// of <c>docs/video-hashing-vectors.json</c>, read at run time rather than copied here.
/// <para>
/// The expectations were generated by running the real dependency chain Stash uses —
/// <c>corona10/goimagehash</c> v1.1.0, <c>disintegration/imaging</c> v1.6.2 and
/// <c>nfnt/resize</c> at the revision Stash pins — over the same formulas. Both sides
/// generate their pixels from the documented formula, so no binary fixtures are needed and
/// the comparison is exact rather than approximate.
/// </para>
/// <para>
/// A failure here means these hashes stopped being comparable with Stash's and with
/// anything else in the ecosystem. It is not a test to adjust to a new value, and not one
/// to change alongside the code it covers.
/// </para>
/// </summary>
public class PerceptualHashReferenceTests
{
    [Theory]
    [MemberData(nameof(TestVectors.Level1), MemberType = typeof(TestVectors))]
    public void Level1_SingleImage_MatchesTheSpecification(
        string kind, int param, int width, int height, string pixelsSha256, string expected)
    {
        var image = ProceduralImages.Create(kind, param, width, height);

        // The input digest first: a generator that differs is the likeliest cause of a
        // mismatch, and it should not be reported as a broken hash.
        Assert.Equal(pixelsSha256, TestVectors.Sha256Hex(image.Pixels));
        Assert.Equal(expected, PerceptualHash.ComputeHex(image));
    }

    [Theory]
    [MemberData(nameof(TestVectors.Level2), MemberType = typeof(TestVectors))]
    public void Level2_Montage_MatchesTheSpecification(
        string kind,
        int tileWidth,
        int tileHeight,
        int montageWidth,
        int montageHeight,
        string montageSha256,
        string expected)
    {
        var montage = TestVectors.BuildMontage(kind, tileWidth, tileHeight);

        Assert.Equal(montageWidth, montage.Width);
        Assert.Equal(montageHeight, montage.Height);
        Assert.Equal(montageSha256, TestVectors.Sha256Hex(montage.Pixels));
        Assert.Equal(expected, PerceptualHash.ComputeHex(montage));
    }

    [Fact]
    public void TheVectorFile_CoversAllThreeLevels()
    {
        // A file that silently lost a level would leave these tests passing while
        // covering less, which is the failure mode a vector-driven suite has to guard
        // against itself.
        Assert.NotEmpty(TestVectors.Level1());
        Assert.NotEmpty(TestVectors.Level2());
        Assert.NotEmpty(TestVectors.Level3());
    }

    [Fact]
    public void FlatBlack_HashesToZero_WhichIsAValueNotAnError()
    {
        // 0000000000000000 is a legitimate hash. A caller treating it as "no hash" drops
        // real values, so it is pinned here as well as in the vector file.
        Assert.Equal("0000000000000000", PerceptualHash.ComputeHex(ProceduralImages.Flat(64, 64, 0)));
    }

    [Fact]
    public void FlatImage_SetsOnlyTheDcBit()
    {
        // With no AC energy every coefficient but the DC one is zero, so exactly one bit
        // may be set and it must be the most significant. This also pins the DC
        // coefficient being kept — a pipeline that discards it returns zero here.
        Assert.Equal("8000000000000000", PerceptualHash.ComputeHex(ProceduralImages.Flat(800, 450, 128)));
    }

    [Fact]
    public void ComputeHex_IsAlways16LowercaseHexCharacters()
    {
        var hash = PerceptualHash.ComputeHex(ProceduralImages.Create("noise", 1, 800, 450));

        // The API validates pHash against ^[0-9A-Fa-f]{16}$.
        Assert.Matches(new Regex("^[0-9a-f]{16}$"), hash);
    }

    [Fact]
    public void Resize_ToTheSameSize_ReturnsTheInputUntouched()
    {
        var image = ProceduralImages.Noise(1, 64, 64);

        // nfnt short-circuits this case, and it is observable: filtering would re-quantise
        // the pixels even at scale 1. It is also why the 64x64 vectors isolate the stages
        // after the resampler.
        Assert.Same(image, BilinearResizer.Resize(image, 64, 64));
    }
}
